### ISSUE TITLE
Calculator or Caluclator?

### ISSUE THREAD

**Issue by Qoyyuum** [Shashank18May/Calculator#2]
The application file and class is `Caluclator`. If you meant to make it as `Calculator`, maybe you should take this chance to refactor and rename your application file. This also needs to be reflected on your README file as well.

**Comment by Shashank18May** [comment]
This was a typo 
that I saw.
Fixed it now.

**Comment by Qoyyuum** [comment]
The latest code changes you made caused 2 more typos on line 118 and line 21.

**Comment by Shashank18May** [comment]
My bad.
Fixed it now.

**Comment by Qoyyuum** [comment]
It's sort of working. No more typos but unable to run application. Please see #3 for more details
