### ISSUE TITLE
Could not find or load main class Main

### ISSUE THREAD

**Issue by Qoyyuum** [Shashank18May/Calculator#3]
After compiling the Calculator file, I wasn't able to run `java Main` to run the app.

```powershell
> java Main
Error: Could not find or load main class Main
```

**Comment by Shashank18May** [comment]
You should run Calculator.

**Comment by Qoyyuum** [comment]
> You should run Calculator.

Can you update the README to reflect that please?

**Comment by Shashank18May** [comment]
Done

**Comment by Qoyyuum** [comment]
Thanks.
