### ISSUE TITLE
After equal to get a result, numbers continue appending to the display

### ISSUE THREAD

**Issue by Qoyyuum** [Shashank18May/Calculator#4]
I was able to get the calculator app working. A quick test I did, 123 + 456  = 579. But the display shows it as "579.0". Then when I press a few more numbers like "789", it appended to the resulting number as "579.0789". Shouldn't the display only be displayed but when a number is pressed after it evaluates, the display should clear for the next new numbers to calculate?

**Comment by Shashank18May** [comment]
It does that so that the user can perform more operations with the result
 If you say I could change that it will empty after a calculation.

**Comment by Qoyyuum** [comment]
For a user to perform more operations with the result should be dealt with when entering a math operator.

Another example of where this is an issue:

123 divide by 0 returns "Infinity". And when entering a number like "456", I get "Infinity456".

That doesn't make sense, does it?

**Comment by Shashank18May** [comment]
Okay so after an operation is finished it will show you the result and next time when you enter a number it will not append it to the result.

**Comment by Qoyyuum** [comment]
And if you enter a math operation (and if the result was not Infinity), then you can continue doing additional calculations.

**Comment by Shashank18May** [comment]
Fixed this bug
